/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth/account/index'
import { Route as AppSandboxIndexRouteImport } from './routes/_app/sandbox/index'
import { Route as AppApiKeysIndexRouteImport } from './routes/_app/api-keys/index'
import { Route as AuthOrganizationsSelectRouteImport } from './routes/_auth/organizations/select'
import { Route as AuthOrganizationsCreateRouteImport } from './routes/_auth/organizations/create'
import { Route as AuthAccountSettingsRouteImport } from './routes/_auth/account/settings'
import { Route as AppApiKeysKeyRouteImport } from './routes/_app/api-keys/$key'
import { Route as AuthOrganizationsActiveSettingsRouteImport } from './routes/_auth/organizations/_active/settings'
import { Route as AuthOrganizationsActiveMembersRouteImport } from './routes/_auth/organizations/_active/members'
import { Route as ApiApiAuthSplatRouteImport } from './routes/_api/api/auth/$'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthRoute,
} as any)
const AppSandboxIndexRoute = AppSandboxIndexRouteImport.update({
  id: '/sandbox/',
  path: '/sandbox/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysIndexRoute = AppApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOrganizationsSelectRoute = AuthOrganizationsSelectRouteImport.update({
  id: '/organizations/select',
  path: '/organizations/select',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsCreateRoute = AuthOrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountSettingsRoute = AuthAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AppApiKeysKeyRoute = AppApiKeysKeyRouteImport.update({
  id: '/api-keys/$key',
  path: '/api-keys/$key',
  getParentRoute: () => AppRoute,
} as any)
const AuthOrganizationsActiveSettingsRoute =
  AuthOrganizationsActiveSettingsRouteImport.update({
    id: '/organizations/_active/settings',
    path: '/organizations/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOrganizationsActiveMembersRoute =
  AuthOrganizationsActiveMembersRouteImport.update({
    id: '/organizations/_active/members',
    path: '/organizations/members',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiApiAuthSplatRoute = ApiApiAuthSplatRouteImport.update({
  id: '/_api/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify': typeof AuthVerifyRoute
  '/': typeof MarketingIndexRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/account/settings': typeof AuthAccountSettingsRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/api-keys': typeof AppApiKeysIndexRoute
  '/sandbox': typeof AppSandboxIndexRoute
  '/account': typeof AuthAccountIndexRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
  '/organizations/members': typeof AuthOrganizationsActiveMembersRoute
  '/organizations/settings': typeof AuthOrganizationsActiveSettingsRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/verify': typeof AuthVerifyRoute
  '/': typeof MarketingIndexRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/account/settings': typeof AuthAccountSettingsRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/api-keys': typeof AppApiKeysIndexRoute
  '/sandbox': typeof AppSandboxIndexRoute
  '/account': typeof AuthAccountIndexRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
  '/organizations/members': typeof AuthOrganizationsActiveMembersRoute
  '/organizations/settings': typeof AuthOrganizationsActiveSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/api-keys/$key': typeof AppApiKeysKeyRoute
  '/_auth/account/settings': typeof AuthAccountSettingsRoute
  '/_auth/organizations/create': typeof AuthOrganizationsCreateRoute
  '/_auth/organizations/select': typeof AuthOrganizationsSelectRoute
  '/_app/api-keys/': typeof AppApiKeysIndexRoute
  '/_app/sandbox/': typeof AppSandboxIndexRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_api/api/auth/$': typeof ApiApiAuthSplatRoute
  '/_auth/organizations/_active/members': typeof AuthOrganizationsActiveMembersRoute
  '/_auth/organizations/_active/settings': typeof AuthOrganizationsActiveSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/sign-in'
    | '/sign-out'
    | '/verify'
    | '/'
    | '/api-keys/$key'
    | '/account/settings'
    | '/organizations/create'
    | '/organizations/select'
    | '/api-keys'
    | '/sandbox'
    | '/account'
    | '/api/auth/$'
    | '/organizations/members'
    | '/organizations/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/sign-in'
    | '/sign-out'
    | '/verify'
    | '/'
    | '/api-keys/$key'
    | '/account/settings'
    | '/organizations/create'
    | '/organizations/select'
    | '/api-keys'
    | '/sandbox'
    | '/account'
    | '/api/auth/$'
    | '/organizations/members'
    | '/organizations/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/_app/dashboard'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/verify'
    | '/_marketing/'
    | '/_app/api-keys/$key'
    | '/_auth/account/settings'
    | '/_auth/organizations/create'
    | '/_auth/organizations/select'
    | '/_app/api-keys/'
    | '/_app/sandbox/'
    | '/_auth/account/'
    | '/_api/api/auth/$'
    | '/_auth/organizations/_active/members'
    | '/_auth/organizations/_active/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiApiAuthSplatRoute: typeof ApiApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/sandbox/': {
      id: '/_app/sandbox/'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys/': {
      id: '/_app/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/organizations/select': {
      id: '/_auth/organizations/select'
      path: '/organizations/select'
      fullPath: '/organizations/select'
      preLoaderRoute: typeof AuthOrganizationsSelectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/create': {
      id: '/_auth/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof AuthOrganizationsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account/settings': {
      id: '/_auth/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthAccountSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/api-keys/$key': {
      id: '/_app/api-keys/$key'
      path: '/api-keys/$key'
      fullPath: '/api-keys/$key'
      preLoaderRoute: typeof AppApiKeysKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/organizations/_active/settings': {
      id: '/_auth/organizations/_active/settings'
      path: '/organizations/settings'
      fullPath: '/organizations/settings'
      preLoaderRoute: typeof AuthOrganizationsActiveSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/_active/members': {
      id: '/_auth/organizations/_active/members'
      path: '/organizations/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof AuthOrganizationsActiveMembersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/api/auth/$': {
      id: '/_api/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppApiKeysKeyRoute: typeof AppApiKeysKeyRoute
  AppApiKeysIndexRoute: typeof AppApiKeysIndexRoute
  AppSandboxIndexRoute: typeof AppSandboxIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppApiKeysKeyRoute: AppApiKeysKeyRoute,
  AppApiKeysIndexRoute: AppApiKeysIndexRoute,
  AppSandboxIndexRoute: AppSandboxIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthAccountSettingsRoute: typeof AuthAccountSettingsRoute
  AuthOrganizationsCreateRoute: typeof AuthOrganizationsCreateRoute
  AuthOrganizationsSelectRoute: typeof AuthOrganizationsSelectRoute
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
  AuthOrganizationsActiveMembersRoute: typeof AuthOrganizationsActiveMembersRoute
  AuthOrganizationsActiveSettingsRoute: typeof AuthOrganizationsActiveSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthAccountSettingsRoute: AuthAccountSettingsRoute,
  AuthOrganizationsCreateRoute: AuthOrganizationsCreateRoute,
  AuthOrganizationsSelectRoute: AuthOrganizationsSelectRoute,
  AuthAccountIndexRoute: AuthAccountIndexRoute,
  AuthOrganizationsActiveMembersRoute: AuthOrganizationsActiveMembersRoute,
  AuthOrganizationsActiveSettingsRoute: AuthOrganizationsActiveSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiApiAuthSplatRoute: ApiApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
