/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApiKeysIndexRouteImport } from './routes/_app/api-keys/index'
import { Route as AuthOrganizationsSelectRouteImport } from './routes/_auth/organizations/select'
import { Route as AuthOrganizationsCreateRouteImport } from './routes/_auth/organizations/create'
import { Route as AppApiKeysKeyRouteImport } from './routes/_app/api-keys/$key'
import { Route as ApiApiAuthSplatRouteImport } from './routes/_api/api/auth/$'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysIndexRoute = AppApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOrganizationsSelectRoute = AuthOrganizationsSelectRouteImport.update({
  id: '/organizations/select',
  path: '/organizations/select',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsCreateRoute = AuthOrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => AuthRoute,
} as any)
const AppApiKeysKeyRoute = AppApiKeysKeyRouteImport.update({
  id: '/api-keys/$key',
  path: '/api-keys/$key',
  getParentRoute: () => AppRoute,
} as any)
const ApiApiAuthSplatRoute = ApiApiAuthSplatRouteImport.update({
  id: '/_api/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/verify': typeof AuthVerifyRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/api-keys': typeof AppApiKeysIndexRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/sign-in': typeof AuthSignInRoute
  '/verify': typeof AuthVerifyRoute
  '/api-keys/$key': typeof AppApiKeysKeyRoute
  '/organizations/create': typeof AuthOrganizationsCreateRoute
  '/organizations/select': typeof AuthOrganizationsSelectRoute
  '/api-keys': typeof AppApiKeysIndexRoute
  '/api/auth/$': typeof ApiApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_app/api-keys/$key': typeof AppApiKeysKeyRoute
  '/_auth/organizations/create': typeof AuthOrganizationsCreateRoute
  '/_auth/organizations/select': typeof AuthOrganizationsSelectRoute
  '/_app/api-keys/': typeof AppApiKeysIndexRoute
  '/_api/api/auth/$': typeof ApiApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/verify'
    | '/api-keys/$key'
    | '/organizations/create'
    | '/organizations/select'
    | '/api-keys'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/verify'
    | '/api-keys/$key'
    | '/organizations/create'
    | '/organizations/select'
    | '/api-keys'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/sign-in'
    | '/_auth/verify'
    | '/_app/api-keys/$key'
    | '/_auth/organizations/create'
    | '/_auth/organizations/select'
    | '/_app/api-keys/'
    | '/_api/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiApiAuthSplatRoute: typeof ApiApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys/': {
      id: '/_app/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/organizations/select': {
      id: '/_auth/organizations/select'
      path: '/organizations/select'
      fullPath: '/organizations/select'
      preLoaderRoute: typeof AuthOrganizationsSelectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/create': {
      id: '/_auth/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof AuthOrganizationsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/api-keys/$key': {
      id: '/_app/api-keys/$key'
      path: '/api-keys/$key'
      fullPath: '/api-keys/$key'
      preLoaderRoute: typeof AppApiKeysKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_api/api/auth/$': {
      id: '/_api/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppApiKeysKeyRoute: typeof AppApiKeysKeyRoute
  AppApiKeysIndexRoute: typeof AppApiKeysIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppApiKeysKeyRoute: AppApiKeysKeyRoute,
  AppApiKeysIndexRoute: AppApiKeysIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthOrganizationsCreateRoute: typeof AuthOrganizationsCreateRoute
  AuthOrganizationsSelectRoute: typeof AuthOrganizationsSelectRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthOrganizationsCreateRoute: AuthOrganizationsCreateRoute,
  AuthOrganizationsSelectRoute: AuthOrganizationsSelectRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiApiAuthSplatRoute: ApiApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
